# Generated by Django 6.0.3 on 2026-04-05 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='rating',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='approved_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='request_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 15, 45, 42, 715318)),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending'),
        ),
    ]
